Working
SSH from container

SSH from host in diff window

Location problems because of curl traffic not using the proxy

Started automatic Firefox settings

diff --git a/src/utils_general b/src/utils_general
--- a/src/utils_general
+++ b/src/utils_general
@@ -1,11 +1,46 @@
 #!/bin/bash
 # Functions for a broad use: from interface to connection and ip location
 
-source ../configs/config.conf
+source configs/config.conf
 
 PROXY_VARS=("port" "host")
 PROXY_PORT_IDX=0
 PROXY_HOST_IDX=1
+
+
+#######################################
+# Adds the key to the ssh agent
+#
+# Globals:
+#   VERBOSE (flag for the verbose mode)
+# Arguments:
+#   None
+# Returns:
+# 	Exit status
+#######################################
+function prepare_ssh_agent() {
+
+    # Check if the SSH agent is running
+    if [ -z "$SSH_AUTH_SOCK" ]; then
+        [[ VERBOSE -eq 1 ]] && echo "SSH agent is not running"
+        ssh-agent -s
+    fi
+
+    # Add the key to the SSH agent
+    if ! ssh-add -l | grep -q "$SSH_PRIVATE_KEY_PATH"; then
+        ssh-add "$SSH_PRIVATE_KEY_PATH"
+
+        local exit_status=$?
+        if [[ "$exit_status" -ne 0 ]];then
+		    log_error "Error adding the ssh key to the ssh agent" "$exit_status"
+			return "$exit_status"
+        fi
+		return "$exit_status";
+    fi 
+
+    [[ VERBOSE -eq 1 ]] && echo "SSH private key added to the SSH system's agent."
+    return 0;
+}
 
 
 #######################################
@@ -84,7 +119,7 @@ function is_server_up() {
 	local readonly TARGET="$1"
 	local PING_NUM_PACKETS="$2"
 	if ping -c $PING_NUM_PACKETS "$TARGET" &> /dev/null; then
-		[[ VERBOSE -eq 1 ]] && echo "Server is up"
+		[[ VERBOSE -eq 1 ]] && printf "\nServer is up"
     	return 0
 	fi
 	return 1
@@ -96,7 +131,7 @@ function is_server_up() {
 # to see the output from ProxyLinks
 #
 # Globals:
-#   None
+#   WINDOW_CREATE (execute ssh on another window)
 # Arguments:
 #   $1: command to connect to the server
 # Returns:
@@ -107,9 +142,9 @@ function create_terminal_tab() {
 
 	local exit_status 
 	if in_container; then
-		"$command" 
+		$(command)
 		exit_status=$? # to avoid capture return value from the if statement
-	elif [[ WINDOW_CREATE -eq 1 ]]; then
+	elif [[ "$WINDOW_CREATE" -eq 1 ]]; then
 		x-terminal-emulator \
 			--title "$WINDOW_TITLE" \
 			--start-as "$WINDOW_STATE" \
@@ -118,7 +153,7 @@ function create_terminal_tab() {
 		exit_status=$? # same reason here as describe above
 	fi 
 
-	if [[ exit_status -ne 0 ]];then
+	if [[ "$exit_status" -ne 0 ]];then
 		log_error "Error creating the interactive terminal window" "$exit_status"
 		return "$exit_status";
 	fi
@@ -144,7 +179,9 @@ function create_terminal_tab() {
 # Returns:
 #	Exit status (0, after the complete execution)
 #######################################
-function know_curr_ip_location() { #TODO on another window, with create tab
+#! curl does NOT use the proxy, 
+#! it needs that the TCP traffic is forced, like with proxychains
+function know_curr_ip_location() {
 	local readonly WANTS_CYCLE="$1"
 
 	if is_server_up "$GEO_API_DOMAIN" "$PING_NUM_PACKETS"; then 
diff --git a/src/utils_proxy b/src/utils_proxy
--- a/src/utils_proxy
+++ b/src/utils_proxy
@@ -1,7 +1,46 @@
 #!/bin/bash
 # Handles proxy settings modification
 
-source utils_general
+source src/utils_general
+
+#######################################
+# Establish the SSH tunnel
+#
+# Globals:
+#   VERBOSE (flag for verbose mode)
+#	HOST_PORT (port of the loopback address)
+#	SERVER_USERNAME (for the proxy server)
+#	SERVER_IP (or the proxy server hostname)
+#	WINDOW_CREATE (execute shh on another window)
+# Arguments:
+#	None
+# Returns:
+# 	Exit status
+#######################################
+function establish_ssh_tunnel() {
+
+	# Can be simplified IF the credentials are in the ~/.ssh/config
+	local command="ssh -D "$HOST_PORT" "
+	if [ "$INTERACTIVE_SSH" -eq 0 ]; then
+    	command+=" -N"
+	fi
+	command+=" -C "$SERVER_USERNAME"@"$SERVER_IP""
+
+	if [ ! "$(in_container)" ] && [ "$WINDOW_CREATE" -eq 1 ]; then
+		create_terminal_tab "$command"
+	else 
+		$command
+	fi
+	
+	local readonly ssh_status=$?
+	if [[ "$ssh_status" -ne 0 ]]; then
+		log_error "Error when connecting via SSH to the proxy server" "$ssh_status"
+		return "$ssh_status"
+	fi
+
+	[[ VERBOSE -eq 1 ]] && echo "SSH tunnel established."
+	return 0;
+}
 
 #######################################
 # ENABLE system proxy settings 
@@ -17,26 +56,30 @@ source utils_general
 #	SSH_PRIVATE_KEY_PATH
 #	SERVER_USERNAME (for the proxy server)
 #	SERVER_IP (or the proxy server hostname)
-# 	SSH_WINDOW (interactive separate window for simultaneous server use)
 # Arguments:
 #	None
 # Returns:
 # 	Exit status
 #######################################
 function proxy_start() {
-	[[ VERBOSE -eq 1 ]] && echo "Setting proxy..."
 
 	# ENABLE proxy in the system settings
 	if in_container; then
 		export HTTP_PROXY=socks5://"$HOST_IP":"$HOST_PORT"
 		export HTTPS_PROXY=socks5://"$HOST_IP":"$HOST_PORT"
-	else 
-		gsettings set org.gnome.system.proxy mode 'manual';
+	else
+		gsettings set org.gnome.system.proxy mode 'manual'
 		gsettings set org.gnome.system.proxy.socks \
-			${PROXY_VARS[$PROXY_PORT_IDX]} "$HOST_PORT" 
-		gsettings set org.gnome.system.proxy.socks \ 
-			${PROXY_VARS[$PROXY_HOST_IDX]} "$HOST_IP"
-	fi 
+			"${PROXY_VARS["$PROXY_PORT_IDX"]}" "$HOST_PORT" 
+		gsettings set org.gnome.system.proxy.socks \
+			"${PROXY_VARS["$PROXY_HOST_IDX"]}" "$HOST_IP"
+		
+		local readonly settings_status=$?
+		if [[ "$settings_status" -ne 0 ]]; then
+			log_error "Error changing proxy settings for the Gnome Environment." "$ssh_status"
+		return "$ssh_status"
+		fi
+	fi
 
 	local readonly settings_status=$?
 	if [[ "$settings_status" -ne 0 ]]; then
@@ -44,30 +87,15 @@ function proxy_start() {
 		return "$settings_status"
 	fi
 
-	# Establish the SSH tunnel
-	# (can be simplified IF the credentials are in the ~/.ssh/config)
-	local command="ssh -D "$HOST_PORT" "
-	if [ "$INTERACTIVE_SSH" -eq 0 ]; then
-    	command+=" -N"
-	fi
-	command+=" -C "$SERVER_USERNAME"@"$SERVER_IP""
-
-	if [ "$(in_container)" -ne 0 ]; then
-		create_terminal_tab "$command"
-	else
-		eval "$command"
-	fi
-	
-	local readonly ssh_status=$?
-	if [[ "$ssh_status" -ne 0 ]]; then
-		log_error "Error when connecting via SSH to the proxy server" "$ssh_status"
-		return "$ssh_status"
+	establish_ssh_tunnel
+	local readonly tunneling_status=$?
+	if [[ "$tunneling_status" -ne 0 ]]; then
+		log_error "Error creating the ssh tunnel with the server" "$tunneling_status"
+		return "$tunneling_status"
 	fi
 
+	[[ VERBOSE -eq 1 ]] && echo "Proxy settings set."
 	return 0;
-
-	#TODO
-	ssh heyAserver@4.232.129.17 2>&1 | tee /proxy_links_logs
 }
 
 
@@ -85,13 +113,16 @@ function proxy_start() {
 function proxy_reset() {
 
 	exec_reset() { # the reset operation itself
-		[[ VERBOSE -eq 1 ]] && printf "\nResetting proxy settings...\n"
 		if in_container; then
 			unset HTTP_PROXY
 			unset HTTPS_PROXY
 		else 
-			gsettings set org.gnome.system.proxy mode 'none'; 
-			return $?
+			gsettings set org.gnome.system.proxy mode 'none'
+			local readonly settings_status=$?
+			if [[ "$settings_status" -ne 0 ]]; then
+				log_error "Error changing proxy settings for the Gnome Environment." "$settings_status"
+			fi
+			return "$settings_status"
 		fi 
     }
 
@@ -105,12 +136,14 @@ function proxy_reset() {
 			local readonly reset_status=$?
             if [[ reset_status -ne 0 ]]; then
 				log_error "Error reseting the proxy settings." "$reset_status"
+				return "$reset_status"
 			fi
         else
 			[[ VERBOSE -eq 1 ]] && echo "Did NOT reset the proxy settings." 
 		fi
     fi
 
+	[[ VERBOSE -eq 1 ]] && printf "Proxy settings reset.\n"
 	return 0;
 }
 
